### ISSUE TITLE
Configuration program arguments no longer being passed in

### ISSUE THREAD

**Issue by bohdon** [rebel-000/CommandlineArgumentsWCheckboxes#16]
Hello, first off amazing plugin, thanks for developing this!

It seems that since a recent update (maybe after I upgraded to Rider 2024.1?), the Program Arguments for a build configuration are no longer being passed through (in addition to any custom args provided by this plugin). The result in my specific situation is that when attempting to run or debug an Unreal project, the specific `.uproject` path is not given, and so it simply launches the editor without any project.

![image](https://github.com/rebel-000/CommandlineArgumentsWCheckboxes/assets/338928/3391ea5b-a6bc-4e70-b1a2-f4270cde9beb)

Cheers!

**Comment by rebel-000** [comment]
Hello!
With the new version, I decided to change the approach to replacing arguments, since there is no universal solution for patching arguments of different types of configurations. 
As for C++ configurations I'm thinking of bringing back old approach soon, since this is the only type of configuration that allows you to patch arguments without pain.
Thanks!
